In [1]:
import numpy as np

In [6]:
x = [0,0,0,0,0,1]
len(x)

6

In [8]:
w1 = np.array([[1,2,3,1,1,0], [1,2,3,5,1,0]])

In [9]:
w1.shape

(2, 6)

In [16]:
w1 = np.random.uniform(-0.8, 0.8, (6, 2))
w2 = np.random.uniform(-0.8, 0.8, (2, 6))

In [12]:
w1

array([[ 0.76930064, -0.34713229],
       [-0.02021082, -0.79934193],
       [-0.3263378 ,  0.24428677],
       [-0.13112731,  0.47644445],
       [-0.64538325, -0.40706052],
       [ 0.27700235,  0.72770356]])

In [21]:
h = np.dot(w1.T, x)
h

array([0.73020139, 0.09619317])

In [19]:
u = np.dot(w2.T, h)
u

array([0.71477545, 0.65935314, 0.23901103, 0.35245098, 0.2350803 ,
       0.50452202])

In [22]:
np.sum(w1, axis = 0)

array([ 1.43497673, -1.13707683])