In [1]:
import numpy as np

In [6]:
x = [0,0,0,0,0,1]
len(x)

6

In [8]:
w1 = np.array([[1,2,3,1,1,0], [1,2,3,5,1,0]])

In [9]:
w1.shape

(2, 6)

In [16]:
w1 = np.random.uniform(-0.8, 0.8, (6, 2))
w2 = np.random.uniform(-0.8, 0.8, (2, 6))

In [12]:
w1

array([[ 0.76930064, -0.34713229],
       [-0.02021082, -0.79934193],
       [-0.3263378 ,  0.24428677],
       [-0.13112731,  0.47644445],
       [-0.64538325, -0.40706052],
       [ 0.27700235,  0.72770356]])

In [21]:
h = np.dot(w1.T, x)
h

array([0.73020139, 0.09619317])

In [19]:
u = np.dot(w2.T, h)
u

array([0.71477545, 0.65935314, 0.23901103, 0.35245098, 0.2350803 ,
       0.50452202])

In [22]:
np.sum(w1, axis = 0)

array([ 1.43497673, -1.13707683])

In [14]:
if not 3 % 3:
    print('hi')

hi


In [8]:
print("working on {}kth line".format(1010 // 1000), end='\r')

In [9]:
test_dict = {'hi':1, 'lol': 2}

In [12]:
test_dict.get('bah', 5) + 1

6

In [13]:
test_dict

{'hi': 1, 'lol': 2}

In [19]:
if '':
    print('lol')

In [24]:
data_path = '../Data/'

In [38]:
import codecs
import pickle
from tqdm import tqdm

In [36]:
with open(data_path+'all-the-news/articles_1_preprocessed.pickle', 'rb') as handle:
    file = pickle.load(handle)

In [33]:
file

[2        [When, Walt, Disney, ’s, Bambi, opened, in, 19...
 4        [SEOUL, South, Korea, North, Korea, ’s, leader...
 5        [LONDON, Queen, Elizabeth, II, who, has, been,...
 6        [BEIJING, President, Tsai, of, Taiwan, sharply...
 10       [With, Donald, J., Trump, about, to, take, con...
 11       [THOMPSONS, Tex, Can, one, of, the, most, prom...
 12       [WEST, PALM, BEACH, Fla., When, Donald, J., Tr...
 13       [This, article, is, part, of, a, series, aimed...
 15       [Finally, The, Second, Avenue, subway, opened,...
 16       [pages, into, the, journal, found, in, Dylann,...
 17       [MUMBAI, India, It, was, a, bold, and, risky, ...
 18       [BAGHDAD, A, suicide, bomber, detonated, a, pi...
 19       [SYDNEY, Australia, The, annual, beach, pilgri...
 20       [When, the, Green, Bay, Packers, lost, to, the...
 21       [Mariah, Carey, suffered, through, a, performa...
 22       [PARIS, When, the, Islamic, State, was, about,...
 23       [Pop, music, and, fashion, nev

In [39]:
wc = {}
for line in (file):
    for word in file:
        wc[word] = wc.get(word, 0) +1  

TypeError: 'Series' objects are mutable, thus they cannot be hashed