In [1]:
import numpy as np

In [6]:
x = [0,0,0,0,0,1]
len(x)

6

In [8]:
w1 = np.array([[1,2,3,1,1,0], [1,2,3,5,1,0]])

In [9]:
w1.shape

(2, 6)

In [16]:
w1 = np.random.uniform(-0.8, 0.8, (6, 2))
w2 = np.random.uniform(-0.8, 0.8, (2, 6))

In [12]:
w1

array([[ 0.76930064, -0.34713229],
       [-0.02021082, -0.79934193],
       [-0.3263378 ,  0.24428677],
       [-0.13112731,  0.47644445],
       [-0.64538325, -0.40706052],
       [ 0.27700235,  0.72770356]])

In [21]:
h = np.dot(w1.T, x)
h

array([0.73020139, 0.09619317])

In [19]:
u = np.dot(w2.T, h)
u

array([0.71477545, 0.65935314, 0.23901103, 0.35245098, 0.2350803 ,
       0.50452202])

In [22]:
np.sum(w1, axis = 0)

array([ 1.43497673, -1.13707683])

In [14]:
if not 3 % 3:
    print('hi')

hi


In [8]:
print("working on {}kth line".format(1010 // 1000), end='\r')

In [9]:
test_dict = {'hi':1, 'lol': 2}

In [12]:
test_dict.get('bah', 5) + 1

6

In [13]:
test_dict

{'hi': 1, 'lol': 2}

In [19]:
if '':
    print('lol')

In [2]:
data_path = '../Data/'

In [3]:
import codecs
import pickle
from tqdm import tqdm

In [4]:
with open(data_path+'all-the-news/articles_1_preprocessed.pickle', 'rb') as handle:
    file = pickle.load(handle)

In [10]:
with open(data_path+'all-the-news/articles_1_0_preprocessed.pickle', 'wb') as handle:
    pickle.dump(file[0], handle)

In [5]:
len(file)

20

In [6]:
len(file[0]), len(file[0])

3525

In [ ]:
wc = {}
for line in (file):
    for word in file:
        wc[word] = wc.get(word, 0) +1  

In [13]:
with open(data_path + '/training_data/period0/wc.dat', 'rb') as handle:
    wc = pickle.load(handle)

In [14]:
with open(data_path + '/training_data/period0/idx2word.dat', 'rb') as handle:
    idx2word = pickle.load(handle)

In [15]:
wf = np.array([wc[word] for word in idx2word])

In [16]:
wf = wf / wf.sum()

In [22]:
ss_t = 0.00001
ws = 1 - np.sqrt(ss_t / wf)

In [23]:
ws

array([-4.08716915,  0.98639357,  0.98123403, ..., -1.07682811,
       -1.07682811, -1.07682811])

In [24]:
ws = np.clip(ws, 0, 1)

In [28]:
vocab_size = len(idx2word)

In [30]:
weights = 4
if weights:
    print('hi')

hi
